"""Render bench/results/*.json to docs/benchmarks/phase1-results.md. Usage: python -m bench.report"""
from __future__ import annotations

import json

from bench.common import RESULTS_DIR, ROOT

OUT = ROOT / "docs" / "benchmarks" / "phase1-results.md"


def _pct(value) -> str:
    return "n/a" if value is None else f"{value * 100:.1f}%"


def render(results: list[dict]) -> str:
    by_kind = lambda prefix: sorted((r for r in results if r["name"].startswith(prefix)), key=lambda r: r["name"])
    out = ["# Phase 1 benchmark results", "", "Generated by `python -m bench.report` from `bench/results/`.", ""]

    out += ["## STT", "", "| engine | device | WER all | WER human | post-speech p50 ms | p95 ms | RTF mean | VRAM +MB |",
            "|---|---|---|---|---|---|---|---|"]
    for r in by_kind("stt_"):
        out.append(f"| {r['engine']} | {r['device']} | {_pct(r['wer_all'])} | {_pct(r['wer_by_source'].get('human'))} "
                   f"| {r['post_speech_ms']['p50']} | {r['post_speech_ms']['p95']} | {r['rtf']['mean']} "
                   f"| {r.get('vram_delta_mb')} |")

    out += ["", "## End of turn", "", "| model | p50 ms | p95 ms | accuracy | human incomplete recall |",
            "|---|---|---|---|---|"]
    for r in by_kind("turn_"):
        human = r["by_source"].get("human", {}).get("incomplete_recall", "n/a")
        out.append(f"| {r['model']} | {r['latency_ms']['p50']} | {r['latency_ms']['p95']} "
                   f"| {r['overall']['accuracy']} | {human} |")

    out += ["", "## TTS", "", "| model | device | first clause audio p50 ms | p95 ms | RTF mean | VRAM +MB |",
            "|---|---|---|---|---|---|"]
    for r in by_kind("tts_"):
        out.append(f"| {r['model']} | {r['device']} | {r['first_clause_audio_ms']['p50']} "
                   f"| {r['first_clause_audio_ms']['p95']} | {r['rtf']['mean']} | {r.get('vram_delta_mb')} |")

    out += ["", "## LLM", "",
            "| model | cold TTFT ms | warm TTFT p50 | p95 | first clause p50 | p95 | tok/s p50 | GPU used peak MB |",
            "|---|---|---|---|---|---|---|---|"]
    for r in by_kind("llm_"):
        w = r["warm"]
        out.append(f"| {r['model']} | {r['cold_ttft_ms']} | {w['ttft_ms']['p50']} | {w['ttft_ms']['p95']} "
                   f"| {w['first_clause_ms']['p50']} | {w['first_clause_ms']['p95']} | {w['tokens_per_s']['p50']} "
                   f"| {r.get('gpu_used_mb_peak')} |")
    return "\n".join(out) + "\n"


def main() -> None:
    results = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(RESULTS_DIR.glob("*.json"))]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(results), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
